# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding Adventures
email: contact.pavlovic@gmail.com
description: This is a blog about my coding adventures, and lessons learned. Mostly software design with a dash of humor.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markonis.github.io" # the base hostname & protocol for your site
twitter_username: InspiringMarko
github_username:  Markonis

# Build settings
markdown: kramdown
